In [1]:
import pandas as pd
df=pd.read_csv('ford.csv')

In [2]:
df.head()

     model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [3]:
X = df.drop(columns = ['price'],axis = 1)
y = df['price']

In [4]:
X

         model  year transmission  mileage fuelType  tax   mpg  engineSize
0       Fiesta  2017    Automatic    15944   Petrol  150  57.7         1.0
1        Focus  2018       Manual     9083   Petrol  150  57.7         1.0
2        Focus  2017       Manual    12456   Petrol  150  57.7         1.0
3       Fiesta  2019       Manual    10460   Petrol  145  40.3         1.5
4       Fiesta  2019    Automatic     1482   Petrol  145  48.7         1.0
...        ...   ...          ...      ...      ...  ...   ...         ...
17961    B-MAX  2017       Manual    16700   Petrol  150  47.1         1.4
17962    B-MAX  2014       Manual    40700   Petrol   30  57.7         1.0
17963    Focus  2015       Manual     7010   Diesel   20  67.3         1.6
17964       KA  2018       Manual     5007   Petrol  145  57.7         1.2
17965    Focus  2015       Manual     5007   Petrol   22  57.7         1.0

[17966 rows x 8 columns]

In [5]:
df.columns

Index(['model', 'year', 'price', 'transmission', 'mileage', 'fuelType', 'tax',
       'mpg', 'engineSize'],
      dtype='object')

In [6]:
from sklearn.preprocessing import LabelEncoder

columns = ['model', 'transmission', 'fuelType']

Xlable = X.copy()  # make a safe copy
label_encoders = {}

for col in columns:
    le = LabelEncoder()
    Xlable[col] = le.fit_transform(Xlable[col].astype(str))  # Convert to string in case of nulls
    label_encoders[col] = le

In [7]:
Xlable

       model  year  transmission  mileage  fuelType  tax   mpg  engineSize
0          5  2017             0    15944         4  150  57.7         1.0
1          6  2018             1     9083         4  150  57.7         1.0
2          6  2017             1    12456         4  150  57.7         1.0
3          5  2019             1    10460         4  145  40.3         1.5
4          5  2019             0     1482         4  145  48.7         1.0
...      ...   ...           ...      ...       ...  ...   ...         ...
17961      0  2017             1    16700         4  150  47.1         1.4
17962      0  2014             1    40700         4   30  57.7         1.0
17963      6  2015             1     7010         0   20  67.3         1.6
17964     11  2018             1     5007         4  145  57.7         1.2
17965     23  2015             1     5007         4   22  57.7         1.0

[17966 rows x 8 columns]

In [8]:
Xlable.columns

Index(['model', 'year', 'transmission', 'mileage', 'fuelType', 'tax', 'mpg',
       'engineSize'],
      dtype='object')

In [9]:
Xlable

       model  year  transmission  mileage  fuelType  tax   mpg  engineSize
0          5  2017             0    15944         4  150  57.7         1.0
1          6  2018             1     9083         4  150  57.7         1.0
2          6  2017             1    12456         4  150  57.7         1.0
3          5  2019             1    10460         4  145  40.3         1.5
4          5  2019             0     1482         4  145  48.7         1.0
...      ...   ...           ...      ...       ...  ...   ...         ...
17961      0  2017             1    16700         4  150  47.1         1.4
17962      0  2014             1    40700         4   30  57.7         1.0
17963      6  2015             1     7010         0   20  67.3         1.6
17964     11  2018             1     5007         4  145  57.7         1.2
17965     23  2015             1     5007         4   22  57.7         1.0

[17966 rows x 8 columns]

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [12]:
X_train, X_test, y_train, y_test = train_test_split(Xlable, y, test_size=0.33, random_state=42)

In [13]:
model2 = LinearRegression()
model2.fit(X_train,y_train)

LinearRegression()

In [14]:
y_pred = model2.predict(X_test)

In [15]:
y_pred

array([ 6157.52473246,  9286.53653694,  9519.82817501, ...,
       19580.21385231,  7384.33202961,  9960.74790235], shape=(5929,))

In [16]:
y_test

17610     6995
7076      8999
1713      7998
1611      5491
16830     3790
         ...
6015     19000
10301    10940
15006    21999
5396      6995
6087     10299
Name: price, Length: 5929, dtype: int64

In [17]:
r2 = r2_score(y_test,y_pred)
r2

0.7310215557390962

In [18]:
n = X_test.shape[0]
p = X_test.shape[1]
adjusted_r2 = 1 - ((1 - r2) * (n - 1)) / (n - p - 1)
print("Adjusted R² Score:", adjusted_r2)

Adjusted R² Score: 0.7306580713549599